In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving iris.data to iris.data
User uploaded file "iris.data" with length 4551 bytes


In [ ]:
import pandas as pd
import io
data=pd.read_csv(io.StringIO(uploaded['iris.data'].decode('utf-8')))
data.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pydot
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np

In [ ]:
dataset = pd.read_csv("iris.data")
dataset

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
model = Sequential()

model.add(Dense(4,input_shape=(4,), activation='relu'))

model.add(Dense(3, activation='softmax'))

In [ ]:
model.compile(optimizer="Adam",loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
12/12 [==============================] - 1s 2ms/step - loss: 2.4247 - accuracy: 0.3361
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 2.2418 - accuracy: 0.3361
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 2.0988 - accuracy: 0.4370
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 1.9721 - accuracy: 0.5714
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 1.8579 - accuracy: 0.5882
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 1.7518 - accuracy: 0.6050
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 1.6535 - accuracy: 0.6134
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 1.5719 - accuracy: 0.6218
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 1.4858 - accuracy: 0.6303
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 1.4142 - accuracy: 0.6303
Epoch 11/

In [ ]:
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

1/1 [==============================] - 0s 154ms/step


In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[12  0  0]
 [ 0 10  0]
 [ 0  0  8]]


In [ ]:
(12+10+8)/30

1.0